### ISSUE TITLE
Not able to install listing-mongo-microservice

### ISSUE THREAD

**Issue by rj00553657** [SaifRehman/ICP-Airways#217]
I tried as you suggested in my issue https://github.com/IBM/icp-airways/issues/9
I am using this repo and also I am using the node 9.8.0 version.

root@mycluster:~/airbus/ICP-Airways-master/icp-backend/listing-mongo-microservice# node -v
v9.8.0

But while installing listing mongo microservice I am getting the following error

root@mycluster:~/airbus/ICP-Airways-master/icp-backend/listing-mongo-microservice# npm i

> webpack-cli@3.3.2 postinstall /root/airbus/ICP-Airways-master/icp-backend/listing-mongo-microservice/node_modules/webpack-cli
> node ./bin/opencollective.js

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/root/airbus/ICP-Airways-master/icp-backend/listing-mongo-microservice/node_modules/webpack-cli/bin/opencollective.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN @angular/core@7.2.15 requires a peer of zone.js@~0.8.26 but none is installed. You must install peer dependencies yourself.
npm WARN express-react-typescript@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ppc64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-cli@3.3.2 postinstall: `node ./bin/opencollective.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-cli@3.3.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-08T06_40_24_283Z-debug.log

**Comment by rj00553657** [comment]
Hi, I tried to install webpack-cli by command also its giving the same error


root@mycluster:~# npm install --save-dev webpack-cli

> webpack-cli@3.3.2 postinstall /root/node_modules/webpack-cli
> node ./bin/opencollective.js

module.js:328
    throw err;
    ^

Error: Cannot find module '/root/node_modules/webpack-cli/bin/opencollective.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
npm WARN webpack-cli@3.3.2 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.
npm WARN my-dream-app@1.0.0 No description
npm WARN my-dream-app@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-cli@3.3.2 postinstall: `node ./bin/opencollective.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-cli@3.3.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-13T10_47_30_992Z-debug.log
root@my

**Comment by SaifRehman** [comment]
npm issue, I tried it my machine I t works, something wrong in your env

**Comment by SaifRehman** [comment]
closing this issue
